[build]
  # Install frontend dependencies and build with CI=false to prevent ESLint warnings from failing
  command = "cd frontend && npm install && CI=false npm run build"
  
  # Frontend build output directory
  publish = "frontend/build"

[build.environment]
  # Build environment
  NODE_ENV = "production"
  NODE_VERSION = "18"
  # Disable ESLint warnings being treated as errors in CI
  DISABLE_ESLINT_PLUGIN = "true"
  # Alternative: Set CI to false to prevent warnings from failing build
  CI = "false"

# Frontend routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects to backend (if using separate backend hosting)
[[redirects]]
  from = "/api/*"
  to = "https://foiyfoshi-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 